services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer-password
    volumes:
      - postgres:/var/lib/postgres/data
    ports: 
      - '5432:5432'

volumes:
  postgres: